### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by ielis**
Setup GitHub workflow for building & deploying the docs to github.io. Note, we may need to enable the github pages in `Settings > Pages` section of the repo. I do not have the superpowers, so, @pnrobinson or @hansenp please enable the pages.

### CODE REVIEW

**Review by pnrobinson — APPROVED** [review]
thanks!!

**Comment by ielis** [comment]
@pnrobinson You must enable the pages in the Settings, otherwise you'll get 404.

**Comment by ielis** [comment]
@pnrobinson @hansenp you must also update the link in the About section of the repo.

**Comment by hansenp** [comment]
Thank you

**Pull request merged**
