### PR TITLE
Alignability memory saver

### PR DESCRIPTION
**Pull request by pnrobinson**
The tests in AlignabilityMapTest are passed.

### CODE REVIEW

**Comment by hansenp** [comment]
For the simple approach, I get a NullPointerException when I try to create viewpoints for one gene on chromsome X.

image

But I do not get a NullPointerException for the extended approach.

**Comment by hansenp** [comment]
Furthermore, I can see that the maps for all chromosomes are read into memory, even though all chromosome groups except the one for chromosome X is empty. Maybe here is potential for improvents of performance.

**Comment by hansenp** [comment]
If I try to open the one viewpoint that is created for the extended approach, I get a `NullPointerException` and the viewpoint tab does not open.

**Comment by pnrobinson** [comment]
@hansenp   -- I think we can merge this now -- it still needs work but it is working without null pointer errors etc.

**Pull request merged**
